name: j2me_installer
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  google_fonts: ^6.2.0
  hive: ^4.0.0-dev.2
  http: ^1.2.1
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/brands/